### ISSUE TITLE
trouble during setup

### ISSUE THREAD

**Issue by AeroSamplerAdmin** [mayooear/private-chatbot-mpt30b-langchain#3]
hi
Great project, wanted to try it, but having these problems during setup:

private-chatbot-mpt30b-langchain$ python ingest.py
Traceback (most recent call last):
  File "/home/im/Downloads/private-chatbot-mpt30b-langchain/ingest.py", line 6, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

and:

private-chatbot-mpt30b-langchain$ poetry run python chat.py
Traceback (most recent call last):
  File "/home/im/Downloads/private-chatbot-mpt30b-langchain/chat.py", line 5, in <module>
    from langchain.callbacks.streaming_stdout import StreamingStdOutCallbackHandler
ModuleNotFoundError: No module named 'langchain'

Am I missing some dependencies or smth else? Seems like I might be missing smth related to LangChain (but already did: pip install langchain)?. rgds, IM

**Comment by saradhix** [comment]
This project uses `poetry` for managing the packages. Please follow the steps given in the installation exactly.
`pip install poetry`
`cd <directory_where_you_cloned>`
`poetry install`
`cp .env.example .env`
`python download_model.py`

**Comment by AeroSamplerAdmin** [comment]
Thx for your answer. I followed these steps before trying to run ingest
etc. Kind rgs

man. 3. jul. 2023 kl. 12.29 skrev Vijayasaradhi ***@***.***>:

**Comment by VEER-TANMAY-SACHIN** [comment]
python download_model.py
Traceback (most recent call last):
  File "/workspace/ai/pgpt/private-chatbot-mpt30b-langchain/download_model.py", line 3, in <module>
    from huggingface_hub import hf_hub_download
ModuleNotFoundError: No module named 'huggingface_hub'

**Comment by VEER-TANMAY-SACHIN** [comment]
I downloaded the bin file in models but now getting this error "  python ingest.py
Traceback (most recent call last):
  File "/workspace/ai/pgpt/private-chatbot-mpt30b-langchain/ingest.py", line 6, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'"

**Comment by saradhix** [comment]
If you have installed poetry and installed the required libraries, you can run
`poetry run python ingest.py`

**Comment by mzubairumt** [comment]
i have installed langchain but still
Traceback (most recent call last):
  File "D:\Office\RandD\Meta\LLAMA\private-chatbot-mpt30b-langchain\ingest.py", line 7, in <module>
    from langchain.docstore.document import Document
ModuleNotFoundError: No module named 'langchain'

**Comment by saradhix** [comment]
If you are using poetry, please use poetry run python <python filename> to activate the right environment. Otherwise you can use pip in a new environment.
