### ISSUE TITLE
NVIDIA CUDA Toolkit libraries error

### ISSUE THREAD

**Issue by Sajjadkhani** [mayooear/private-chatbot-mpt30b-langchain#4]
I am following all the instructions but I am getting the following error when I run `python ingest.py`.

Traceback (most recent call last):
  File "/home/skhani/anaconda3/envs/llm/lib/python3.11/site-packages/torch/__init__.py", line 168, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/home/skhani/anaconda3/envs/llm/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: libcufft.so.10: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/skhani/Documents/Recent/LLM/private-chatbot-mpt30b-langchain-main/ingest.py", line 162, in <module>
    main()
  File "/home/skhani/Documents/Recent/LLM/private-chatbot-mpt30b-langchain-main/ingest.py", line 126, in main
    embeddings = HuggingFaceEmbeddings(model_name=embeddings_model_name)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/skhani/anaconda3/envs/llm/lib/python3.11/site-packages/langchain/embeddings/huggingface.py", line 51, in __init__
    import sentence_transformers
  File "/home/skhani/anaconda3/envs/llm/lib/python3.11/site-packages/sentence_transformers/__init__.py", line 3, in <module>
    from .datasets import SentencesDataset, ParallelSentencesDataset
  File "/home/skhani/anaconda3/envs/llm/lib/python3.11/site-packages/sentence_transformers/datasets/__init__.py", line 1, in <module>
    from .DenoisingAutoEncoderDataset import DenoisingAutoEncoderDataset
  File "/home/skhani/anaconda3/envs/llm/lib/python3.11/site-packages/sentence_transformers/datasets/DenoisingAutoEncoderDataset.py", line 1, in <module>
    from torch.utils.data import Dataset
  File "/home/skhani/anaconda3/envs/llm/lib/python3.11/site-packages/torch/__init__.py", line 228, in <module>
    _load_global_deps()
  File "/home/skhani/anaconda3/envs/llm/lib/python3.11/site-packages/torch/__init__.py", line 189, in _load_global_deps
    _preload_cuda_deps(lib_folder, lib_name)
  File "/home/skhani/anaconda3/envs/llm/lib/python3.11/site-packages/torch/__init__.py", line 154, in _preload_cuda_deps
    raise ValueError(f"{lib_name} not found in the system path {sys.path}")
ValueError: libcublas.so.*[0-9] not found in the system path ['/home/skhani/Documents/Recent/LLM/private-chatbot-mpt30b-langchain-main', '/home/skhani/anaconda3/envs/llm/lib/python311.zip', '/home/skhani/anaconda3/envs/llm/lib/python3.11', '/home/skhani/anaconda3/envs/llm/lib/python3.11/lib-dynload', '/home/skhani/anaconda3/envs/llm/lib/python3.11/site-packages']
(llm) skhani@skhani-Precision-7760 ~/Documents/Recent/LLM/private-chatbot-mpt30b-langchain-main$ poetry install
Installing dependencies from lock file

No dependencies to install or update
(llm) skhani@skhani-Precision-7760 ~/Documents/Recent/LLM/priv
ate-chatbot-mpt30b-langchain-main$ on311.zip', '/home/skhani/anaconda3/envs/llm/lib/python3.11', '/home/skhani/anaconda3/envs/llm/lib/python3.11/lib-dynload', '/home/skhani/anaconda3/envs/llm/lib/python3.11/site-packages']khani/anaconda3/envs/llm/lib/python3.11/site-packages']

**Comment by SemenMartynov** [comment]
It helped me:
`$ pip3 install torch torchvision torchaudio`
(yes, with pip, no poetry)

**Comment by SemenMartynov** [comment]
...or try to assemble a more convenient set of packages for your hardware on the pytorch website:
https://pytorch.org/get-started/locally/

**Comment by Sajjadkhani** [comment]
> It helped me: `$ pip3 install torch torchvision torchaudio` (yes, with pip, no poetry)

Thank you. Now it is working.
